require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-hc
Style/Documentation:
  Enabled: false
AllCops:
  NewCops: enable
RSpec/MultipleExpectations:
  Max: 2
Metrics/MethodLength:
  Max: 30
Metrics/BlockLength:
  Max: 30
Layout/LineLength:
  Max: 120
Metrics/AbcSize:
  Max: 30
